### ISSUE TITLE
The index store at [...] does not contain data for the following targets

### ISSUE THREAD

**Issue by gavrillas** [peripheryapp/periphery#641] opened 2023-07-20 08:36 UTC
I updated to 2.15.0 from 2.12.3 and it broke my CI pipeline.
I am using fastlane to build the project and run tests. In order to optimise the pipeline I reused the fastlane build for scanning previously. 

It was working properly before the update, but since that i am getting the following error: 

`The index store at '["DerivedData/Index.noindex/DataStore"]' does not contain data for the following targets: MyProject. Either the index store is outdated, or you have requested to scan targets that have not been built. For Xcode projects, the chosen schemes must build all of the chosen targets.`

This is how my lane looks like:

```
scan(
      project: "MyProject.xcodeproj",
      scheme: "MyProject",
      skip_build: false,
      build_for_testing: true,
      clean: true,
      derived_data_path: "./DerivedData",
      xcargs: '-skipPackagePluginValidation COMPILER_INDEX_STORE_ENABLE="YES"' 
)
```

and this is my periphery config file:
```
project: MyProject.xcodeproj
schemes:
- MyProject
targets:
- MyProject
- Package1
- Package2
- Package3
- Package4
retain_public: true
strict: true
skip_build: true
index_store_path: "DerivedData/Index.noindex/DataStore/"
```

How can I solve this issue? Thanks.

**Comment by AntonKozlovskyi** [comment] 2023-07-25 11:20
Faced same problem. Was caused by installing `Periphery` via CocoaPods.
Fixed by calling ```Pods/Periphery/periphery scan``` instead of ``` periphery scan```

**Comment by gavrillas** [comment] 2023-07-27 07:03
> Faced same problem. Was caused by installing `Periphery` via CocoaPods.
> Fixed by calling `Pods/Periphery/periphery scan` instead of ` periphery scan`

Well, actually we don't use CocoaPods. It's installed via Homebrew.

**Comment by VaslD** [comment] 2023-08-11 17:19
Run `periphery` with `--verbose` and look for the `xcodebuild` command used to build the project. It would look like this:

```plaintext
* Building MyProject...
[shell] /bin/sh -c xcodebuild -project '/Users/vasld/Developer/Projects/Demo/Demo.xcodeproj' -scheme 'App' -parallelizeTargets -derivedDataPath '/Users/vasld/Library/Caches/com.github.peripheryapp/DerivedData-6a94a430' -quiet build CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf" COMPILER_INDEX_STORE_ENABLE="YES"
```

Run this command in a separate Shell, if you see the following log:

> --- xcodebuild: WARNING: Using the first of multiple matching destinations:

It means that `periphery` didn't find the expected IndexStore because it was building the project for the wrong platform.

I had to remove Mac support (Designed for iPad & Catalyst) from my iOS project in order for `periphery` to work.

When `--destination` was not given to `xcodebuild` it chooses a random destination, it may then build an iOS app for "My Mac", or simply fails because a connected iPhone has a lower iOS version than the deployment target. Anything that can show up in the Xcode project destination picker may be targeted by `xcodebuild` even those unavailable for deployment, and it's plain stupid. IMO command-line invocations should at least target generic destinations (excluding "My Mac", connected iPhones, and installed Simulators); since Apple won't be doing that, `periphery` better add `--destination`s to build commands.

**Comment by alexclp** [comment] 2023-08-15 14:16
My project supports iPhone, iPad, Catalyst and tvOS and I was getting the same error. I didn't get anything interesting by running the xcodebuild line directly.

However what made it work for me is to keep only iPhone + iPad as the supported targets. A good workaround but not useful if you want to analyse code that the other targets are using as well (assuming your code has a few branches where it might guard away Catalyst/tvOS code). 

I imagine the issue is for projects where Catalyst is supported and the xcodebuild command defaults to building to macOS native for some reason. It would help if the setup command asks you what target device family you want to build for.

**Comment by tcamin** [comment] 2023-08-16 15:30
We have a fairly simple CocoaPods based project and are facing a similar issue since updating from version 2.13.0 which was the last working release.

We always build for simulator and at least in our specific case the issue seems to be connected with the main unit's target triple extracted [here](https://github.com/peripheryapp/periphery/blob/a2eb3799457c415dda86c7814283295fe7b06b89/Sources/PeripheryKit/Indexer/SwiftIndexer.swift#L60) being `arm64-apple-ios14.0-simulator` instead of `arm64-apple-ios14.0` which is extracted from build settings.

**Comment by ileitch** [comment] 2023-08-19 08:23
You can choose the appropriate destination, e.g: `periphery scan ... -- -destination 'platform=iOS Simulator`. Does that work for you all?

**Comment by tcamin** [comment] 2023-08-21 07:41
That did it, I was passing `-destination 'generic/platform=iOS Simulator'` instead which apparently was wrong. Thanks!

**Comment by CedrickLoavies** [comment] 2023-09-18 15:53
Similar problem; below the same command is being ran on two versions; `2.9` which still works and `2.15.1` which does not recognize my index store.

 2.9.0:
```
++ Utilities/Periphery/periphery scan --skip-build --verbose --index-store-path /Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex/DataStore/ --report-exclude '**/SwiftGen/*.swift'
+ PERIPHERY_OUTPUT='[version] 2.9.0
[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
[shell] /usr/bin/env xcodebuild -version
Xcode 14.3.1
Build version 14E300c
[configuration:begin]
index_store_path: /Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex/DataStore/
project: MyApp.xcodeproj
report_exclude:
- '\''**/SwiftGen/*.swift'\''
schemes:
- MyApp - Test
skip_build: true
targets:
- MyApp
verbose: true
[configuration:end]
* Inspecting project...
[xcode:project] Loading /MyApp/MyApp.xcodeproj
[shell] /usr/bin/env xcodebuild -project /MyApp/MyApp.xcodeproj -list -json
* Indexing...
[index:swift:phase:one]...
```

2.15.1
```
++ Utilities/Periphery/periphery scan --skip-build --verbose --index-store-path /Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex/DataStore/ --report-exclude '**/SwiftGen/*.swift'
error: The index store at '["/Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex"]' does not contain data for the following targets: MyApp. Either the index store is outdated, or you have requested to scan targets that have not been built. For Xcode projects, the chosen schemes must build all of the chosen targets.
+ PERIPHERY_OUTPUT='[version] 2.15.1
[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
[shell] /usr/bin/env xcodebuild -version
Xcode 14.3.1
Build version 14E300c
[configuration:begin]
index_store_path:
- /Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex/DataStore/
project: MyApp.xcodeproj
report_exclude:
- '\''**/SwiftGen/*.swift'\''
schemes:
- MyApp - Test
skip_build: true
targets:
- MyApp
verbose: true
[configuration:end]
* Inspecting project...
[xcode:project] Loading /MyApp/MyApp.xcodeproj
[shell] /usr/bin/env xcodebuild -project /MyApp/MyApp.xcodeproj -list -json
[shell] /usr/bin/env xcodebuild -project /MyApp/MyApp.xcodeproj -showBuildSettings -json -target MyApp
* Indexing...
[index:swift] Reading /Users/ci/Library/Developer/Xcode/DerivedData/MyApp-hbycaslbzsztiwelepancwbakmxz/Index.noindex
[index:swift] Source file not indexed
```

**Comment by pm-dev** [comment] 2023-09-18 21:36
Also started happening for me after the update to 2.15.

When running `periphery scan` normally, everything runs successfully, however periphery is building for platform `iphoneos` rather than `iphonesimulator`

I run into this same issue when specifying `--index-store-path` with a DataStore that comes from building for iphonesimulator. No build settings differ when building the Debug configuration for iphonesimulator vs iphoneos so I'm not sure what the difference might be. The targets listed after "does not contain data for the following targets:" have definitely been built.

Happens with xcodebuild from xcode 14 and xcode 15

**Comment by zwaldowski** [comment] 2023-09-19 00:27
I'm trying to debug this with a `master` build equivalent to 2.15.1 and I'm seeing the target triple get resolved to `x86_64-apple-macos14.0` after the `showBuildSettings` step even for a project with Catalyst, etc. support removed.

**Comment by zwaldowski** [comment] 2023-09-19 00:59
On Xcode 15.0 final (15A240d), one can see that several combinations of parameters to `-showBuildSettings` that work to actually work to build the product successfully (f.ex., `scheme` + `workspace` + `destination`) show wildly incorrect values for `-showBuildSettings`, leading to an incorrect target triple. Definitely worthy of an Xcode bug.

**Comment by liamnichols** [comment] 2023-09-25 13:39
I'm seeing a similar issue coming from 2.13.0 to 2.15.2 while using Xcode 14.3.1 still. Thanks to @zwaldowski's hint, I can also see that our triple is also wrong:

```
po (sourceFiles[file]?.compactMapSet { $0.triple } ?? []) // From the `-showBuildSettings`
▿ 1 element
  - 0 : "arm64-apple-ios14.0"

po try indexStore.target(for: unit) // From the IndexStore
▿ Optional<String>
  - some : "arm64-apple-ios14.0-simulator"
```

In my use case, i'm building (and running unit tests) outside of periphery, and then invoking scan with the following arguments:

```
$ periphery scan --disable-update-check --format json --skip-build --index-store-path ./derivedData/Index.noindex/DataStore --verbose
```

I tried appending `-- -destination` to the invocation, but that didn't work.. I think maybe because it's only passed by Periphery to `xcodebuild build` and not `-showBuildSettings`? But anyway, I also tried calling `xcodebuild` directly to test and it seems that the `-destination` specifier is ignored anyway:

```
$ xcrun xcodebuild -project ./Mise/Mise.xcodeproj -showBuildSettings -json -destination 'platform=iOS Simulator,id=3EE8D47D-64D4-4E53-94E0-6786EBE577BA' -target MiseCore | grep "CURRENT_ARCH\|LLVM_TARGET_TRIPLE_VENDOR\|LLVM_TARGET_TRIPLE_OS_VERSION"
      "CURRENT_ARCH" : "arm64",
      "LLVM_TARGET_TRIPLE_OS_VERSION" : "ios14.0",
      "LLVM_TARGET_TRIPLE_VENDOR" : "apple",
```

I'm not sure if that is a bug with Xcode, or if it's just not supported? `man xcodebuild` doesn't seem to suggest that `-destination` is supported

> Lists the build settings for targets in a project or workspace. Does not initiate a build. Use with -target or with -scheme. With -scheme, optionally pass a build action (such as build or test) to use targets from the matching scheme action.

**Closed** 2023-10-30 09:07 UTC
Labels: question
