### ISSUE TITLE
Recognising used variables as unused

### ISSUE THREAD

**Issue by NagarajBasarkod** [peripheryapp/periphery#596] opened 2023-03-21 11:07 UTC
Variables are declared in super class, but used in subclasses or used as typecasted in other classes are treated as unused.

ex: 
```
class Water {
var color: String?
}

class Resources {
  func naturalResource() {
    let waterOptional = water()
    if let water = waterOptional {
      water.color = "Clear"
    }
  }
}
```
according to periphery, color is an unused variable in class Water

**Comment by ileitch** [comment] 2023-03-21 19:35
Thank you @NagarajBasarkod. It would be extremely helpful if you provide a sample project so that I can reproduce the issue. Thanks!

**Comment by ileitch** [comment] 2023-06-17 09:53
Closing due to lack of sample project to reproduce the problem.

**Closed by ileitch** 2023-06-17 09:53 UTC
