### ISSUE TITLE
False positives for Protocol type aliases

### ISSUE THREAD

**Issue by trant** [peripheryapp/periphery#32] opened 2019-05-15 10:14 UTC
```swift
typealias PersistenceProtocol = ThreadPersistenceProtocol & MessagePersistenceProtocol

struct Persistence: PersistenceProtocol {
 (...)
}
```

The Persistence struct is being used everywhere but I am still getting warnings for PersistenceProtocol, ThreadPersistenceProtocol, MessagePersistenceProtocol being unused

**Comment by booiiing** [comment] 2019-09-04 13:06
Isn't this a duplicate of #10?

**Closed** 2020-11-12 11:25 UTC
Labels: needs investigation
