### ISSUE TITLE
False positives when using Combine and subscriptions 

### ISSUE THREAD

**Issue by utahwithak** [peripheryapp/periphery#564] opened 2023-01-05 19:00 UTC
Ran periphery and am seeing quite a few false positives, one that sticks out is this one: 

``` swift
: warning: Property 'subscriptions' is unused
```

While in fact it is being used, here's an example of the class:

``` swift
final class Foo {

    private var subscriptions = Set<AnyCancellable>()

    init() {
         bar.somePublisher
              .receive(on: RunLoop.main)
              .sink(receiveValue: { _ in ... })
              .store(in: &subscriptions)
    }

```
Another example: 
``` swift
@MainActor
class BarViewModel {
    let baz: CurrentValueSubject<Baz?, Never>

    private var subscriptions = Set<AnyCancellable>()

    init() {
        super.init()

        baz
            .dropFirst()
            .map {
                $0?.id
            }
            .assign(to: \.bazID, on: settings)
            .store(in: &subscriptions)
    }
}
```
results in:
`: warning: Property 'subscriptions' is unused`
That is the only place it is being used in the class but it definitely is being used and needed.

**Comment by ileitch** [comment] 2023-01-06 12:16
In the second example, the use of `@MainActor` may be the cause. Unfortunately, there's a bug in Swift 5.7 preventing Periphery from observing some references. I think it may be fixed in the upcoming 5.8 release though. To work around this in the meantime, you could try adding a `// periphery:ignore` comment to the initializer.

As for the first example, I don't see any reason this would cause `subscriptions` to be identified as unused.

**Comment by utahwithak** [comment] 2023-01-06 13:25
I had left off `@MainActor` from the first example. That explains it a lot of our other false positives. We'll try again with 5.8. Thanks.

**Comment by ileitch** [comment] 2023-01-06 15:19
Alrighty, I'll close this as a duplicate of https://github.com/peripheryapp/periphery/issues/550 then. Please keep an eye on that issue, I'll close it out when I can confirm Swift 5.8 fixes the bug.

**Closed by ileitch** 2023-01-06 15:19 UTC
