### ISSUE TITLE
Error Dectection when using guard let

### ISSUE THREAD

**Issue by inotetw** [peripheryapp/periphery#667] opened 2023-10-26 03:27 UTC
## following code

```
import RxSwift
import RxCocoa
import RxBinding

class TestDateCell: UICollectionViewCell {

    typealias ViewModel = TestDateModel
    private var viewModel: ViewModel?

    func configureBinding(_ viewModel: ViewModel? = nil) {
        guard let viewModel else {
            return
        }

        self.viewModel = viewModel

        let inputs = ViewModel.Input()
        let output = viewModel.transform(inputs)

        output.title ~> titleLabel.rx.text ~ disposeBag
   }
}
```

```
import RxSwift
import RxCocoa

class TestDateModel {

    private let disposeBag: DisposeBag = .init()
    private let titleRelay = BehaviorRelay<String?>(value: nil)

    struct Input {}

    struct Output {
        let title: Driver<String?>
    }

    func transform(_ inputs: Input) -> Output {
       Output(
            title: titleRelay.asDriver()
        )
    }

    func setTitle(_ title: String?) {
        titleRelay.accept(title)
    }
}
```

```
import RxSwift
import RxCocoa
class Contorller: UIViewController {
    let cell = TestDateCell()
    let viewModel = TestDateCell.ViewModel()

    override func viewDidLoad() {
        super.viewDidLoad()
        cell.configureBinding(viewModel)
        viewModel.setTitle("Test")
    }  
}
```

but it will show viewModel is unused

**Comment by ileitch** [comment] 2023-10-29 16:33
It's not clear from your example exactly what you are saying is unused. Is it the property, the typealias or the function parameter? Please provide an exmaple project that demonstrates the issue.

**Comment by inotetw** [comment] 2023-10-31 05:07
i updated my example ^^

**Comment by inotetw** [comment] 2023-10-31 05:09
> It's not clear from your example exactly what you are saying is unused. Is it the property, the typealias or the function parameter? Please provide an exmaple project that demonstrates the issue.


i updated my example ^^

**Comment by geraldWilliam** [comment] 2023-12-07 21:00
@inotetw I copied your code into a new project and added the Rx dependencies. I had to make a couple of changes to get it to compile but I think I understand what you're seeing now. Do you get the following message for the `viewModel` property in TestDateCell?

`warning: Property 'viewModel' is assigned, but never used`

If so, the message is accurate. When you call `let output = viewModel.transform(inputs)`, you're calling transform on the viewModel parameter, not the property. If you replace that line with `let output = self.viewModel!.transform(inputs)`, you'll no longer see the warning.

**Comment by ileitch** [comment] 2023-12-18 16:52
Closing due to no clear reproduction. Please provide an example project demonstrating the issue.

**Closed by ileitch** 2023-12-18 16:52 UTC
Labels: question
