### ISSUE TITLE
Xcode 11 support

### ISSUE THREAD

**Issue by iwheelbuy** [peripheryapp/periphery#51] opened 2019-09-18 12:32 UTC
I got `error: unknownTokenKind("ellipsis")`. I believe it is Xcode 11 issue, because 10.3 works fine. And I'm not alone: https://github.com/peripheryapp/periphery/issues/39#issuecomment-508944676

It would be great to have Xcode 11 support? Thanks

**Comment by prrane** [comment] 2019-11-04 17:45
ditto

**Comment by ileitch** [comment] 2019-11-07 17:57
Duplicate of #49

**Closed by ileitch** 2019-11-07 17:57 UTC
