### ISSUE TITLE
keyNotFound "minimumVersion"

### ISSUE THREAD

**Issue by vahotm** [peripheryapp/periphery#765] opened 2024-07-05 08:41 UTC
I am receiving the following error. Is that error also from tuist?

```
error: (DecodingError) keyNotFound(CodingKeys(stringValue: "minimumVersion", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "requirement", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"minimumVersion\", intValue: nil) (\"minimumVersion\").", underlyingError: nil))
```

**Comment by KevinDoremy** [comment] 2024-07-07 03:52
Same here

**Comment by ileitch** [comment] 2024-08-04 11:27
Possible because the project does not speciy a minimum version for remote packages, and xcodeproj expects one: https://github.com/tuist/XcodeProj/blob/951e9397e59dd1cabb369c1e8894643f7be22019/Sources/XcodeProj/Objects/SwiftPackage/XCRemoteSwiftPackageReference.swift#L43

**Comment by ileitch** [comment] 2024-09-15 14:38
Closing as this is not a bug in Periphery. Please open a bug report at https://github.com/tuist/XcodeProj if this continues to affect your project.

**Closed by ileitch** 2024-09-15 14:38 UTC
Labels: needs investigation
