### ISSUE TITLE
Running Periphery on a Linux Project That Uses a Different Version of Swift

### ISSUE THREAD

**Issue by xanderdunn** [peripheryapp/periphery#181] opened 2020-11-10 20:02 UTC
I have a project that can only be built with [Swift for Tensorflow](https://github.com/tensorflow/swift/blob/master/Installation.md), either on Linux or macOS.  Periphery does not build using Swift for Tensorflow:
```
$ swift run periphery
/home/xander/dev/my_model/.build/checkouts/Yams/Sources/Yams/Representer.swift:130:21: error: static member 'pow' cannot be used on instance of type 'Double'
        let radix = pow(10.0, Double(precision))
                    ^~~
                    Double.
```
This issue is unique to Swift for Tensorflow and does not reproduce on macOS or Linux with Swift 5.3 or Swift dev trunk 2020-11-05.

Despite this, I can still successfully run periphery on my Swift for Tensorflow project on macOS like this:
```
$ brew tap peripheryapp/periphery && brew install periphery
$ which periphery
/usr/local/bin/periphery
$ periphery version
2.0.1
$ which swift
/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.11.xctoolchain/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM db8896f3f345af2, Swift 61684f62a6132c0)
Target: x86_64-apple-darwin19.6.0
$ periphery scan --setup
# Everything builds and successfully outputs list of unused items
```
Although periphery wasn't built with Swift for Tensorflow v0.11, it does successfully build my project using it.

I tried a similar feat on Linux but didn't succeed. First I build the periphery binary using Swift 5.3:
```
$ which swift
/home/xander/swift-5.3-RELEASE-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-linux-gnu
$ swift run periphery
# It successfully builds and gives output:
USAGE: periphery <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  scan                    Scan for unused code
  check-update            Check for available update
  version                 Display this version of Periphery

  See 'periphery help <subcommand>' for detailed help.
$ cp .build/debug/periphery ./
```

Now I switch my env back to Swift for Tensorflow and run the copied periphery binary:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 55d27a5828, Swift 6a5d84ec08)
Target: x86_64-unknown-linux-gnu
$ ./periphery
free(): invalid next size (fast)
Aborted (core dumped)
```

Do you have thoughts on why I can run the macOS periphery binary against a Swift for Tensorflow project, but this doesn't work in my Linux situation? Maybe my action to copy the binary to an arbitrary location isn't valid?

**Comment by ileitch** [comment] 2020-11-11 10:43
The compiler errors from Yams is fixed, though not yet release: https://github.com/jpsim/Yams/pull/273. I've requested a new release here: https://github.com/jpsim/Yams/issues/287. I'll update & release Periphery once that's done.

In your example where you just received the help output, you're missing the `scan`command. The full command is `swift run periphery scan`. I've updated the README to make that clear.

I'm not surprised that copying the binary doesn't work.

**Comment by xanderdunn** [comment] 2020-11-11 14:37
> In your example where you just received the help output, you're missing the scan command. The full command is swift run periphery scan. I've updated the README to make that clear.

I wasn't trying to receive anything more than the help output on that step. Running `swift run periphery scan` at that step would give me compiler errors. You can see the compiler was set to Swift 5.3-RELEASE. My project does NOT build with 5.3. It requires Swift for Tensorflow. Hence, I tried to build periphery with 5.3 and then use that built binary to run periphery on a project using Swift for Tensorflow. 

Maybe this is my misunderstanding: I assumed that Homebrew distributes a binary. Does it instead simply run the project's Makefile? If that's the case, then when I originally installed periphery on my Mac via Homebrew, it would've been built with Swift for Tensorflow, not 5.3.

> I'm not surprised that copying the binary doesn't work.

Installing the binary via Homebrew works, whereas copying the binary doesn't work. What are the differences?

**Comment by ileitch** [comment] 2020-11-11 16:05
You're correct, the Homebrew package distributes a binary built for macOS. Only SwiftPM is supported on Linux. Yams will be cutting a new version shortly, so we should be able to resolve building with Swift for Tensorflow soon.

**Comment by ileitch** [comment] 2020-11-11 16:59
I've merged the updated Yams version into master. Could you checkout master and build it (`swift build`) and try it with your Tensorflow project?

**Comment by xanderdunn** [comment] 2020-11-11 18:22
Thanks @ileitch! I was able to build periphery master on macOS with Swift for Tensorflow 0.11. 

On Ubuntu 18.04 I was also able to successfully build using Swift for Tensorflow 0.10 with `swift build --build-tests --enable-test-discovery`. However, running it fails:

```
$ swift run periphery scan --targets "PlutusModelApp","PlutusModelLib" --retain-public
[193/193] Linking periphery
* Inspecting project...
* Building PlutusModelLib...
* Building PlutusModelApp...
* Indexing...
Error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSy
ntax
```

**Comment by xanderdunn** [comment] 2020-11-11 18:30
The Swift for Tensorflow I'm using:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 55d27a5828, Swift 6a5d84ec08)
Target: x86_64-unknown-linux-gnu
```

I see that lib_InternalSwiftSyntaxParser.so does exist inside that toolchain:
```
/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/lib/swift/linux/lib_InternalSwiftSyntaxParser.so
```

I have it set in `LD_LIBRARY_PATH`:
```bash
export LD_LIBRARY_PATH=/home/xander/swift-tensorflow-RELEASE-0.10-cuda10.2-cudnn7-ubuntu18.04/usr/lib/swift/linux:$LD_LIBRAR  Y_PATH
```
But perhaps it isn't finding it?

**Comment by ileitch** [comment] 2020-11-12 10:55
It's not that the library can't be found, the problem is that SwiftSyntax isn't compatible with Swift for Tensorflow 0.10. Each release of SwiftSyntax is tied directly to specific Swift release, which it validates when the library is loaded: https://github.com/apple/swift-syntax/blob/fd784856ac5106c2e33c27295fe336c6ab2be162/Sources/SwiftSyntax/gyb_generated/Misc.swift#L1954

This version string `Swift version 5.3-dev (LLVM 55d27a5828, Swift 6a5d84ec08)` seems to suggest that 0.10 was forked from a development version of Swift 5.3, for which there's no corresponding SwiftSyntax release.

I'm afraid there's not really anything I can do to resolve this. You could fork SwiftSyntax and try to get it working with 0.10 if you really wanted, but since 0.11 seems to work without issue, I'm not sure it's wort the effort.

**Comment by xanderdunn** [comment] 2020-11-12 12:19
Thanks for investigating.

Swift for Tensorflow is always forked from latest Swift dev trunk. Here is 0.11:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.11-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM db8896f3f345af2, Swift 61684f62a6132c0)
Target: x86_64-unknown-linux-gnu
```
Although the version string is still "5.3-dev", this is ahead of 5.3-RELEASE. The version string is "5.3-dev" still today on dev trunk 2020-11-05. I'm unsure how to match the `swiftparse_syntax_structure_versioning_identifier` to specific versions of Swift to know which versions of Swift are supported by SwiftSyntax. 

On both macOS and Linux I run into a different problem when trying to `swift run periphery` in my project with S4TF 0.11:
```
$ rm Package.resolved
$ rm -rf .build
$ swift run periphery scan --targets "ModelApp","ModelLib" --retain-public
...
error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
```
This is probably some specific combination of dependencies in my project's Package.swift.

However, I can confirm that when I install periphery via Homebrew on Mac, I can successfully run `periphery scan` on my S4TF 0.11 project.

I imagine it's not worth much more effort to get periphery working with S4TF. This would allow me to include it in my projects' continuous integration, but I'm currently able to use it manually on Mac via the Homebrew installation. My original goal in this issue was to build periphery with Swift 5.3 and then run it against a S4TF project. This works on macOS using the Homebrew installed periphery binary to scan a S4TF 0.11 project.

**Comment by ileitch** [comment] 2020-11-12 14:46
> On both macOS and Linux I run into a different problem when trying to swift run periphery in my project with S4TF 0.11:
>
> ```
> $ rm Package.resolved
> $ rm -rf .build
> $ swift run periphery scan --targets "ModelApp","ModelLib" --retain-public
> ...
> error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
> ```

Is this using the `master` build of Periphery? New in master is an unreleased change change for Swift 5.2 support, so the Package.swift conditionally depends on different versions of SwiftSyntax. Is this output coming from Periphery, or from Swift? Does Periphery attempt to build any targets before you get this error? Are you seeing any changes made to your Package.resolved?

**Comment by xanderdunn** [comment] 2020-11-12 16:44
> Is this using the master build of Periphery?

Yes. Here it is in my Package.swift:
```swift
        .package(name: "Periphery",
                 url: "https://github.com/peripheryapp/periphery",
                 .branch("master"))
```

> Is this output coming from Periphery, or from Swift? 

It's coming from Swift.

> Does Periphery attempt to build any targets before you get this error?

No. This is very early in the build processing where it's resolving dependencies.  The error occurs before it even starts building periphery.  Here is a more complete output:
```
$ swift run periphery scan --targets "ModelApp","ModelLib" --retain-public
Updating https://github.com/peripheryapp/periphery
Updating https://github.com/attaswift/BigInt
Updating https://github.com/apple/swift-nio-ssl.git
Updating https://github.com/krzyzanowskim/CryptoSwift.git
Updating https://github.com/apple/swift-nio.git
Updating https://github.com/apple/swift-nio-extras.git
Updating https://github.com/swift-server/async-http-client.git
Updating https://github.com/apple/swift-nio-transport-services.git
Updating https://github.com/googleapis/google-auth-library-swift
Updating https://github.com/apple/swift-log.git
Updating https://github.com/jkandzi/Progress.swift
Updating https://github.com/vapor/websocket-kit
Updating https://github.com/fabianfett/pure-swift-json.git
Updating https://github.com/kareman/SwiftShell
Updating https://github.com/swift-server/swift-backtrace.git
Updating https://github.com/1024jp/GzipSwift.git
Fetching https://github.com/tuist/xcodeproj
Fetching https://github.com/apple/swift-syntax
Fetching https://github.com/apple/swift-argument-parser
Fetching https://github.com/kylef/PathKit
Fetching https://github.com/tadija/AEXML
Fetching https://github.com/kateinoigakukun/swift-indexstore
Fetching https://github.com/jpsim/Yams
Removing https://github.com/apple/swift-nio.git
Removing https://github.com/apple/swift-nio-extras.git
Removing https://github.com/apple/swift-nio-transport-services.git
Removing https://github.com/attaswift/BigInt
Removing https://github.com/scottrhoyt/SwiftyTextTable.git
Removing https://github.com/apple/swift-nio-ssl.git
Cloning https://github.com/kylef/PathKit
Resolving https://github.com/kylef/PathKit at 1.0.0
Cloning https://github.com/apple/swift-argument-parser
Resolving https://github.com/apple/swift-argument-parser at 0.3.1
Cloning https://github.com/tuist/xcodeproj
Resolving https://github.com/tuist/xcodeproj at 7.17.0
Cloning https://github.com/kateinoigakukun/swift-indexstore
Resolving https://github.com/kateinoigakukun/swift-indexstore at 0.1.2
Cloning https://github.com/apple/swift-syntax
Resolving https://github.com/apple/swift-syntax at 0.50300.0
Cloning https://github.com/tadija/AEXML
Resolving https://github.com/tadija/AEXML at 4.6.0
Cloning https://github.com/jpsim/Yams
Resolving https://github.com/jpsim/Yams at 4.0.1
Updating https://github.com/saeta/penguin.git
Updating /Users/xander/dev/SwiftArrow
Updating https://github.com/peripheryapp/periphery
Updating https://github.com/swift-server/async-http-client.git
Updating https://github.com/kareman/SwiftShell
Updating https://github.com/tuist/xcodeproj
Updating https://github.com/vapor/websocket-kit
Updating https://github.com/fabianfett/pure-swift-json.git
Updating https://github.com/jpsim/Yams
Updating https://github.com/googleapis/google-auth-library-swift
Updating https://github.com/jkandzi/Progress.swift
Updating https://github.com/apple/swift-syntax
Updating https://github.com/swift-server/swift-backtrace.git
Updating https://github.com/1024jp/GzipSwift.git
Updating https://github.com/apple/swift-argument-parser
Updating https://github.com/krzyzanowskim/CryptoSwift.git
Updating https://github.com/tadija/AEXML
Updating https://github.com/kateinoigakukun/swift-indexstore
Updating https://github.com/kylef/PathKit
Updating https://github.com/apple/swift-log.git
Fetching https://github.com/attaswift/BigInt
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/apple/swift-nio-transport-services.git
Fetching https://github.com/apple/swift-nio-extras.git
Fetching https://github.com/apple/swift-nio-ssl.git
Fetching https://github.com/tuist/XcodeProjCExt
Cloning https://github.com/attaswift/BigInt
Resolving https://github.com/attaswift/BigInt at 5.2.0
Cloning https://github.com/apple/swift-nio-transport-services.git
Resolving https://github.com/apple/swift-nio-transport-services.git at 1.9.0
Cloning https://github.com/apple/swift-nio-extras.git
Resolving https://github.com/apple/swift-nio-extras.git at 1.7.0
Cloning https://github.com/tuist/XcodeProjCExt
Resolving https://github.com/tuist/XcodeProjCExt at 0.1.0
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 2.23.0
Resolving https://github.com/tadija/AEXML at 4.4.0
Cloning https://github.com/apple/swift-nio-ssl.git
Resolving https://github.com/apple/swift-nio-ssl.git at 2.10.0
error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
```

> Are you seeing any changes made to your Package.resolved?

In a `git diff Package.resolved`, almost everything has changed. Most packages have changed position in the file, AEXML has been added, PathKit has been added, SwiftIndexStore has been added, and periphery has been updated:
```diff
         "package": "Periphery",
         "repositoryURL": "https://github.com/peripheryapp/periphery",
         "state": {
-          "branch": null,
-          "revision": "3c6f64642d96c0e2d6012ff92c9b112b48e739a3",
-          "version": "2.0.1"
+          "branch": "master",
+          "revision": "6169d93cce985fe7ba18a94b162cc86314767475",
+          "version": null
         }
```

**Comment by ileitch** [comment] 2020-11-13 11:01
Hmm, I don't see anything obviously wrong. A few things to try:

1. Does this only happen using `swift run`, or does it also fail with just `swift build`?
2. You've a mix of packages ending with `.git` and some without. I've seen SPM have issues with this myself, try removing the `.git` suffix or adding it to all dependencies.
3. Does this only happen with the `master` version of Periphery? What about 2.0.1?

**Comment by xanderdunn** [comment] 2020-11-13 18:38
Thanks for the continued support!

> Does this only happen using swift run, or does it also fail with just swift build?

`swift build` runs without any issues on my project with Swift for Tensorflow 0.11, but this doesn't build Periphery. Periphery is listed in my dependencies, but none of my targets depend on it, so it's only built when I explicitly `swift run periphery`. So it seems to build fine when it's ignoring the periphery dependency.

> You've a mix of packages ending with .git and some without. I've seen SPM have issues with this myself, try removing the .git suffix or adding it to all dependencies.

Interesting, I didn't know this. I removed all the `.git`s so that none of them have it. Running `swift run periphery scan --targets "ModelApp","ModelLib" --retain-public` produced the same result:
```
error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
```

> Does this only happen with the master version of Periphery? What about 2.0.1?

I changed it from master to 2.0.1, ran `swift package update`:
```
Resolving https://github.com/peripheryapp/periphery at 2.0.1
```
and then `swift run periphery scan --targets "PlutusModelApp","PlutusModelLib" --retain-public`.  Unfortunately the result is the same:
```
error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
```

**Comment by ileitch** [comment] 2020-11-14 13:26
Hmm, I'm not really sure what else to suggest. This is only an issue with S4TF, right? `swift run periphery` works fine with Swift 5.3?

**Comment by xanderdunn** [comment] 2020-11-14 14:39
Correct, it doesn't occur with Swift 5.3. Periphery successfully builds with `swift run periphery scan --targets "ModelApp","ModelLib" --retain-public`, but then periphery's scan fails to build my project due to the S4TF dependency of my code.

The next question is whether it occurs on Swift dev trunk, so I tried on one of the latest:
```
$ which swift
/home/xander/swift-DEVELOPMENT-SNAPSHOT-2020-11-05-a-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM ea8eac6ba760b92, Swift e8151ee2b27776f)
Target: x86_64-unknown-linux-gnu
$ swift run periphery scan --targets "ModelApp","ModelLib" --retain-public
```
This also successfully builds periphery and starts the scan on my project and then fails to build my project due to the S4TF dependency. This means that it's specific to S4TF, or that the issue has been resolved on Swift dev trunk in the time between S4TF 0.11 was branched off and the the 2020-11-05 dev trunk version.

To test this hypothesis, I tried the current release candidate of Swift for Tensorflow 0.12rc2:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.12-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 69d8678431d3eee, Swift e1aef96b7fea59b)
Target: x86_64-unknown-linux-gnu
```
This also successfully builds periphery!  So this means that it was likely an issue on Swift dev trunk that has been resolved. S4TF 0.12 doesn't appear to have the `_InternalSwiftSyntaxParser` issue, either.

Unfortunately I can't use any version of S4TF higher than 0.10 due to [this Swift complier bug](https://bugs.swift.org/browse/SR-13491). However, this is not a periphery issue, so we can probably close this.

**Comment by xanderdunn** [comment] 2020-11-15 15:27
As a result of attaswift/BigInt#77, our project now builds on S4TF 0.11 and 0.12. Unfortunately, it looks like we do still run into the `_InternalSwiftSyntaxParser` issue:
```
$ which swift
/home/xander/swift-tensorflow-RELEASE-0.12-cuda10.2-cudnn7-ubuntu18.04/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM 69d8678431d3eee, Swift e1aef96b7fea59b)
Target: x86_64-unknown-linux-gnu
$ swift run periphery scan --targets "ModelApp","ModelLib" --retain-public
...
[218/218] Linking periphery

* Build Completed!
* Inspecting project...
* Building PlutusModelLib...
* Building PlutusModelApp...
* Indexing...
Error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
```

I think I just didn't get far enough in the build in my earlier test to hit this with S4TF 0.12rc2.

Do you know how to match SwiftSyntax versions with compatible Swift versions?

**Comment by ileitch** [comment] 2020-11-16 10:23
Even if we could bypass this version check, I'm doubtful the parser would succeed, since doesn't S4TF contain additional syntax not present in standard Swift?

**Comment by xanderdunn** [comment] 2020-11-16 14:48
I would think the same, except that I successfully run periphery on our project using S4TF 0.11* when I install periphery on macOS via Homebrew:

```
$ which periphery
/usr/local/bin/periphery
$ periphery version
2.0.1
$ which swift
/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.11.xctoolchain/usr/bin/swift
$ swift --version
Swift version 5.3-dev (LLVM db8896f3f345af2, Swift 61684f62a6132c0)
Target: x86_64-apple-darwin19.6.0
$ periphery scan --targets "PlutusModelApp","PlutusModelLib" --retain-public
* Inspecting project...
* Building PlutusModelLib...
* Building PlutusModelApp...
* Indexing...
* Analyzing...

* No unused code detected.
```

Why does that work? Perhaps the `_InternalSwiftSyntaxParser` version check is a compile-time check only? periphery doesn't build with S4TF, but it runs with it.

My original goal in this issue was to replicate this success on Linux: Build periphery with Swift 5.3 and then run it with S4TF.

\* S4TF 0.12 has not yet been released for macOS.

**Comment by ileitch** [comment] 2020-11-16 17:27
This works on macOS because Periphery includes a copy of `lib_InternalSwiftSyntaxParser.dylib`, [as recommended](https://github.com/apple/swift-syntax#embedding-swiftsyntax-in-an-application) by SwiftSyntax. So despite your current Swift being S4TF, it's actually using a copy of `lib_InternalSwiftSyntaxParser.dylib` pulled from the Xcode version I use to build Periphery for macOS.

On Linux there's no prebuilt binary, so it's always going to use the parser lib from the current toolchain. On Linux you can workaround this by explicitly using the Swift 5.3 parser:

```
$ which swift
/opt/swift-tensorflow-RELEASE-0.11-ubuntu20.04/usr/bin/swift
$ LD_PRELOAD=/opt/swift-5.3-RELEASE-ubuntu20.04/usr/lib/swift/linux/lib_InternalSwiftSyntaxParser.so ./.build/debug/periphery scan
```

There's no guarantee it'll be able to parse your source files correctly though. However since it does already appear to work for you on macOS, perhaps it will on Linux too. I guess the S4TF syntax changes are syntactically compatible with the Swift 5.3 parser, perhaps just not semantically?

**Closed** 2020-11-17 18:49 UTC
