### ISSUE TITLE
False positive of `unused initializer`

### ISSUE THREAD

**Issue by videolist** [peripheryapp/periphery#534] opened 2022-10-24 21:51 UTC
Periphery scan fails on this one: https://app.bitrise.io/build/74f775e5-43bc-497e-8833-b6af7c87240e
It complains about an unused initializer. The initializer has default value for one of the parameters which is omitted on the call site. So initializer IS being used but with less parameters than in the full signature. Is that some new check and can it be ignored?  It's not part of the required check but looks like it causes other required checks to be stuck in limbo.

**Comment by videolist** [comment] 2022-10-25 00:50
Turns out the issue was due to the `@MainActor` on the class that has that initializer. Once that was removed it went through. So looks like the periphery check can't handle @MainActor properly.

**Comment by ileitch** [comment] 2022-11-20 10:25
@videolist I can't access that Bitrise build. Could you please provide a code snippet that demonstrates the issue?

**Comment by ileitch** [comment] 2022-12-31 12:16
Closing as duplicate of https://github.com/peripheryapp/periphery/issues/550

**Closed by ileitch** 2022-12-31 12:16 UTC
Labels: question
