### ISSUE TITLE
Github CI throws error: 'Either the index store is outdated, or you have requested to scan targets that have not been built'

### ISSUE THREAD

**Issue by Jasperav** [peripheryapp/periphery#502] opened 2022-06-09 12:10 UTC
I have a separate job which runs the periphery scan, but it fails with this error:

```
stdout: "* Inspecting project...\n* Building project-iosUITests...\n* Building project-iosTests...\n* Building project-ios...\n* Indexing...\n",
    stderr: "error: The index store at '/Users/runner/Library/Caches/com.github.peripheryapp/DerivedData-f3bd6041-79ffde3d/Index/DataStore' does not contain data for the following targets: project-ios, project-iosTests, project-iosUITests. Either the index store is outdated, or you have requested to scan targets that have not been built.\n",
```

This is my command:

`periphery scan --strict --clean-build`

I just clone my project, brew install periphery and run that command in a github ci job. Am I missing something?

**Comment by alex851209** [comment] 2022-06-21 03:17
Same issue here

**Comment by ileitch** [comment] 2022-09-29 04:53
Can you please include the output from the `--verbose` option?

**Comment by dungi** [comment] 2022-10-17 10:21
@Jasperav did you managed to fixed this issue?

**Comment by Jasperav** [comment] 2022-10-17 10:49
@dungi nah I gave up :(

**Comment by jzwc** [comment] 2022-10-21 13:57
We had similar/same issue too, perhaps related to an Xcode upgrade (to 14.0.1 in our case). The error in verbose log was related to inability of some files indexing (cannot reproduce it anymore, thus no exact printout).

When I used older Xcodes, or current Xcode 4.1 beta, the error disappears… also when I run periphery in Xcode 14.0.1 build phase script again. 

Cleaning caches and derived data did not helped itself, although it might play a role with combination of the Xcode versions switching.

**Comment by dungi** [comment] 2022-10-25 06:50
Hmm... didn't work for me. I updated to Xcode 14.1. But thanks anyway @jzwc for your information.

**Comment by ileitch** [comment] 2022-11-12 18:25
Does this happen consistently or is it intermittent? Are you certain that the targets you requested to analyze are actually built by the scheme?

**Comment by jzwc** [comment] 2022-11-28 14:38
It is back for me. See (redacted) log, the redacted parts seems to be ok.

- The `[index:swift] Source file not indexed` were recently added to the project (not locally, however, the code is a git checkout for a code review of some changes made by somebody else). 
- The workspace and all targets compile as expected without errors (with just some warnings). 
- The examined Xcode target also runs `swiftlint` and `swiftformat` in a build phase.

```
% periphery scan --workspace "REDACTED.xcworkspace" --schemes REDACTED --targets REDACTED,"REDACTED Tests","Unit Tests" --report-exclude "REDACTED/**/*.swift" --retain-objc-accessible --verbose
[version] 2.10.0
[shell] /bin/zsh -lc env
[shell] /usr/bin/env swift -version
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
[shell] /usr/bin/env xcodebuild -version
Xcode 14.1
Build version 14B47b
[configuration:begin]
report_exclude:
- "REDACTED/**/*.swift"
retain_objc_accessible: true
schemes:
- REDACTED
targets:
- REDACTED
- REDACTED Tests
- Unit Tests
verbose: true
workspace: REDACTED
[configuration:end]
* Inspecting project...
[xcode:workspace] Loading REDACTED.xcworkspace
[xcode:project] Loading REDACTED.xcodeproj
[xcode:project] Loading REDACTED/TestApp.xcodeproj
[shell] /usr/bin/env xcodebuild -workspace REDACTED.xcworkspace -list -json
[shell] /usr/bin/env xcodebuild -workspace REDACTED.xcworkspace -showBuildSettings -scheme REDACTED build test
* Building REDACTED...
[shell] /bin/sh -c xcodebuild -workspace 'REDACTED.xcworkspace' -scheme 'REDACTED' -parallelizeTargets -derivedDataPath 'REDACTED/Library/Caches/com.github.peripheryapp/DerivedData-8baa28e1-c65005c9' -quiet build-for-testing CODE_SIGNING_ALLOWED="NO" ENABLE_BITCODE="NO" DEBUG_INFORMATION_FORMAT="dwarf"
* Indexing...
[index:swift] Source file not indexed: REDACTED.swift
[index:swift] Source file not indexed: REDACTED.swift
[index:swift] Source file not indexed: REDACTED.swift
[index:swift] Source file not indexed: REDACTED.swift
[index:swift] Source file not indexed: REDACTED.swift
[index:swift] Source file not indexed: REDACTED.swift
error: The index store at 'REDACTED/Library/Caches/com.github.peripheryapp/DerivedData-8baa28e1-c65005c9/Index/DataStore' does not contain data for the following targets: REDACTED. Either the index store is outdated, or you have requested to scan targets that have not been built.
```

**Comment by spipau** [comment] 2022-12-20 19:33
Same here, Periphery doesn't work any more with Xcode 14.2 when I run `BuildTools/periphery scan --report-exclude "**/R.generated.swift" --verbose` I get:

> The index store at '/Users/…/Library/Caches/com.github.peripheryapp/DerivedData-cdc2f99d-beef84d0/Index/DataStore' does not contain data for the following targets: TARGET. Either the index store is outdated, or you have requested to scan targets that have not been built.

**Comment by jpeckner** [comment] 2022-12-23 00:34
@ileitch I'm also seeing essentially the [same error output](https://github.com/peripheryapp/periphery/issues/502#issuecomment-1360058912) that @spipau saw with Xcode 14.2, Periphery 2.10.2 (installed with Homebrew). Everything worked fine with Xcode 13.4 previously. Hope this can be fixed soon (but no worries if it's done after New Year's - thank you for all you do on Periphery!).

**Comment by ileitch** [comment] 2023-01-02 12:36
@jzwc @spipau @jpeckner Could you please answer these questions to help me diagnose the issue:
1. Does the error occur consistently every time?
2. Does the `--clean-build` option fix it?
3. Is it always the same build target that's not found?
4. Is there anything special about the files that are missing from the index?
5. Are you running periphery locally or in CI? If locally, is it from the command line or from an Xcode build phase?
6. If you copy and run the `xcodebuild` command performed by Periphery, does it succeed? (obtained from using `--verbose`)
7. Does the error occur after switching between different Xcode versions?

**Comment by ileitch** [comment] 2023-01-02 17:18
I've included a potential fix for this in 2.10.3, could you all please give it a try?

**Comment by jpeckner** [comment] 2023-01-03 16:17
@ileitch 2.10.3 worked like a charm for me, thank you!

**Comment by spipau** [comment] 2023-01-09 14:32
@ileitch thank you for your patience, I was offline over the holidays. I just updated to the latest version you published recently and now everything works again 🥳 

FYI I run it locally in a Xcode 14.2 Build Phase with `BuildTools/periphery scan --report-exclude "**/R.generated.swift"`

Thank you very much! 🙏

**Comment by oguzparlak** [comment] 2023-01-09 16:03
In my case it was xcscheme issue.
I have an SPM package and somehow the scheme was generated incorrect. 
Might be related to Xcode version.
Just go to `.swiftpm/xcode/xcshareddata/xcschemes` in your package folder. and use this scheme template.

```
<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "1410"
   version = "1.3">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "YourTargetName_YourTargetName"
               BuildableName = "YourTargetName_YourTargetName"
               BlueprintName = "YourTargetName_YourTargetName"
               ReferencedContainer = "container:">
            </BuildableReference>
         </BuildActionEntry>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "YourTargetName"
               BuildableName = "YourTargetName"
               BlueprintName = "YourTargetName"
               ReferencedContainer = "container:">
            </BuildableReference>
         </BuildActionEntry>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "NO"
            buildForArchiving = "NO"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "YourTargetNameTests"
               BuildableName = "YourTargetNameTests"
               BlueprintName = "YourTargetNameTests"
               ReferencedContainer = "container:">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      shouldUseLaunchSchemeArgsEnv = "YES">
      <Testables>
         <TestableReference
            skipped = "NO">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "YourTargetNameTests"
               BuildableName = "YourTargetNameTests"
               BlueprintName = "YourTargetNameTests"
               ReferencedContainer = "container:">
            </BuildableReference>
         </TestableReference>
      </Testables>
   </TestAction>
   <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "NO"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Release"
      shouldUseLaunchSchemeArgsEnv = "YES"
      savedToolIdentifier = ""
      useCustomWorkingDirectory = "NO"
      debugDocumentVersioning = "YES">
      <MacroExpansion>
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "YourTargetName_YourTargetName"
            BuildableName = "YourTargetName_YourTargetName"
            BlueprintName = "YourTargetName_YourTargetName"
            ReferencedContainer = "container:">
         </BuildableReference>
      </MacroExpansion>
   </ProfileAction>
   <AnalyzeAction
      buildConfiguration = "Debug">
   </AnalyzeAction>
   <ArchiveAction
      buildConfiguration = "Release"
      revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>

```

Replace `YourTargetName` with your target name and try again.

**Comment by jzwc** [comment] 2023-01-09 17:20
Confirming, the upgrade 2.10.2 -> 2.11.0 works for me as well.

Thanks!

**Closed** 2023-01-14 12:15 UTC
Labels: bug, question

**Comment by paxos** [comment] 2023-11-09 19:47
I see this issue again with version `2.16.0`  and Xcode `15.0.1`:

```
* Indexing...
[index:swift] Reading /Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED-gxiutlgnrjnecrayhfvdoooxenpi/Index.noindex/DataStore
[index:swift] Source file not indexed: /Users/REDACTED/Developer/REDACTED.git/REDACTED/Models/REDACTED.swift
error: The index store at '["/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED-gxiutlgnrjnecrayhfvdoooxenpi/Index.noindex/DataStore"]' does not contain data for the following targets: REDACTED. Either the index store is outdated, or you have requested to scan targets that have not been built. For Xcode projects, the chosen schemes must build all of the chosen targets.
```
