### ISSUE TITLE
False positive with conditional init

### ISSUE THREAD

**Issue by iressler** [peripheryapp/periphery#419] opened 2021-11-01 19:31 UTC
I found a false positive with a generic object that has a convenience initializer in a conditional extension.

Some additional information I found while creating the minimally reproducing case:
- Removing the first parameter in the init (`defaultValue`) removes the false positive.
- Having the same initializer in the main body (not a conditional extension) removes the false positive.

Sample code & project, and Periphery output below.

**`Periphery output`**:
```sh
$ periphery version
2.8.1
$ periphery scan
* Inspecting project...
* Building periphery-conditional-init...
* Indexing...
* Analyzing...

<repo-path>/periphery-conditional-init/periphery-conditional-init/ValueHolder.swift:21:15: warning: Initializer 'init(defaultValue:)' is unused
```

**`ValueHolder`**:
```Swift
class ValueHolder<ValueType> {
  let getValue: () -> ValueType

  init(defaultValue: ValueType, getValue _getValue: @escaping () -> ValueType?) {
    self.getValue = {
      _getValue() ?? defaultValue
    }
  }
}

extension ValueHolder where ValueType == Bool {
  convenience init(defaultValue: ValueType) {
    self.init(defaultValue: defaultValue) {
      return defaultValue
    }
  }
}

extension ValueHolder {
  static func defaultFalse() -> ValueHolder<Bool> {
    ValueHolder<Bool>(defaultValue: false)
  }
}
```

**`ContentView`**:
```Swift
struct ContentView: View {
  var route: ValueHolder = .defaultFalse()

  var body: some View {
    if route.getValue() {
      Text("Name")
    } else {
      Text("No name")
    }
  }
}
```
[sample Xcode project](https://github.com/peripheryapp/periphery/files/7455684/periphery-conditional-init.zip)

**Comment by ileitch** [comment] 2021-11-27 18:30
Thanks for an exemplary bug report, @iressler, it makes investigating so much easier!

Unfortunately this appears to be caused by a known bug in Swift: https://bugs.swift.org/browse/SR-7093. I'm trying to work my way through and fix [these bugs](https://github.com/peripheryapp/periphery#known-bugs) myself since Apple doesn't appear to be interested. However I've not much time these days, so it's very unlikely any fix will be included in Swift 5.6. Hopefully I'll be able to fix it in time for 5.7 or 6.0, whichever is coming next.

**Closed** 2023-09-26 09:16 UTC
Labels: bug, apple bug
