### ISSUE TITLE
error: SourceKit index request failed for file 'xxx.swift': 'xxx.swift' is not part of the input files

### ISSUE THREAD

**Issue by chinnasamymca** [peripheryapp/periphery#56] opened 2019-11-05 10:19 UTC
I am getting an error running on Xcode 11 

error: SourceKit index request failed for file 'xxx.swift': 'xxx.swift' is not part of the input files

I am using one Target and multiple schemas.

**Comment by ileitch** [comment] 2019-11-05 10:22
Duplicate of #49

**Closed by ileitch** 2019-11-05 10:22 UTC
