### ISSUE TITLE
PreviewProvider

### ISSUE THREAD

**Issue by jonnyijapan** [peripheryapp/periphery#650] opened 2023-09-04 08:04 UTC
If a struct is only used from PreviewProvider, it would be helpful to have a way to treat that struct as unused. Is this possible?

**Comment by ileitch** [comment] 2023-09-04 08:50
Duplicate of https://github.com/peripheryapp/periphery/issues/524. I will address this soon, it seems like a popular issue.

**Closed by ileitch** 2023-09-04 08:50 UTC
