### ISSUE TITLE
@MainActor declarations appear as unused code

### ISSUE THREAD

**Issue by carlosnaguilera** [peripheryapp/periphery#550] opened 2022-12-13 17:41 UTC
From Xcode 14 periphery is not handling correctly declarations with the `@MainActor` attribute.

For example, if we add `@MainActor` to a protocol declaration, when using Xcode 14, periphery marks all protocol methods as unused. Although they are used.
In fact, it is the same code that we have for Xcode 13. In Xcode 13 periphery works fine and it doesn't consider these methods as unused.

Tested on Xcode 14.0.1, 14.1 and 14.2 RC. Running periphery 2.10.2

On a different issue (https://github.com/peripheryapp/periphery/issues/534) users reached to the same conclusion. I'm opening this new issue just to give more visibility to the real problem.

Here you can find a super easy example of the problem: https://github.com/peripheryapp/periphery/issues/534#issuecomment-1344279987

Thank you very much for maintaining this great tool

**Comment by ileitch** [comment] 2022-12-31 12:16
Thanks @carlosnaguilera. Unfortunately, this looks like a bug in the Swift compiler. I'm planning to fix some other compiler bugs soon, so I'll take a look at how hard this one would be to solve.

**Comment by ileitch** [comment] 2023-01-09 10:18
I believe this issue in fixed in the upcoming Swift 5.8, I'm just waiting for the first beta to confirm.

**Comment by ileitch** [comment] 2023-02-18 11:53
Confirmed, this is fixed in 5.8.

**Closed by ileitch** 2023-02-18 11:53 UTC
Labels: bug, apple bug
