### ISSUE TITLE
Local Swift packages in workspace are not scanned

### ISSUE THREAD

**Issue by harrisonfriia** [peripheryapp/periphery#626] opened 2023-06-29 09:26 UTC
I have a workspace that contains an xcodeproj with my app target, and a handful of local Swift packages that the app depends on. The local swift packages are top-level in the workspace, alongside the project for my app. The packages are all iOS specific, so I'm building separately and passing the index-store-path:

```
xcodebuild -quiet -scheme $my_app_target -destination 'generic/platform=iOS' -derivedDataPath $my_index_store_path build

periphery scan --skip-build --index-store-path "${my_index_store_path}/Index.noindex/DataStore" --verbose
```

`.periphery.yml`:
```
retain_objc_accessible: true
schemes:
# list of all my local swift package schemes
targets:
- MyAppTarget
workspace: MyWorkspace.xcworkspace
```

The command runs without any errors and detects unused code, but only in my app target. `[index:swift:phase:one]` and `[index:swift:phase:two]` only list Swift files that are part of my app target, and do not list any files in my local packages.

 It looks like https://github.com/peripheryapp/periphery/pull/455 added support for this, but maybe it only works for local packages that are part of a project, not a workspace.

**Comment by ileitch** [comment] 2023-07-01 08:45
https://github.com/peripheryapp/periphery#how-to-use
> To get coherent results from Periphery, it's crucial to understand the implications of the build targets you choose to analyze. For example, imagine a project consisting of three targets: App, Lib and Tests. The App target imports Lib, and the Tests targets imports both App and Lib. If you were to provide all three to the --targets option then Periphery will be able to analyze your project as a whole. However, if you only choose to analyze App and Lib, but not Tests, Periphery may report some instances of unused code that are only referenced by Tests. Therefore when you suspect Periphery has provided an incorrect result, it's important to consider the targets that you have chosen to analyze.

You need to also specify the local package targets, try using `scan --setup` to begin with.

**Comment by harrisonf-ledger** [comment] 2023-07-08 08:55
I used `scan --setup` but it does not find the local package targets in the workspace. If I manually specify the local package targets and run scan, I get `error: Target 'MyLocalPackageTarget' does not exist in 'MyWorkspace.xcworkspace'.`

I did get it to work by moving all my local packages inside my apps _project,_ which is inside the workspace, but that's a change I have to undo after running the tool since I need my local packages to be top-level in the workspace.

**Comment by harrisonfriia** [comment] 2023-07-08 08:55
I used scan --setup but it does not find the local package targets in the workspace. If I manually specify the local package targets and run scan, I get error: Target 'MyLocalPackageTarget' does not exist in 'MyWorkspace.xcworkspace'.

I did get it to work by moving all my local packages inside my apps project, which is inside the workspace, but that's a change I have to undo after running the tool since I need my local packages to be top-level in the workspace.

**Comment by ileitch** [comment] 2023-08-19 08:40
@harrisonfriia Can you please provide a sample project that demonstrates the issue? It's very hard for me to implement a fix for this without being able to inspect the pbxproj.

**Comment by im-jersh** [comment] 2023-09-01 00:00
i have a similar setup with a workspace containing a project and a set of local dependencies that live in a directory in the root folder along with the workspace and project. 

i'm also seeing similar behavior where Periphery only returns results for the application target when what i'm really interested in is seeing unused code in the local frameworks that isn't referenced anywhere in the the application target's dependency graph.

i'll try to find some time to setup an example workspace and report back

**Comment by baharevmv** [comment] 2023-09-07 21:26
I got similar troubles with local dependencies. I'm working on the task of adding local packages (as in the example of @im-jersh) to the scanning area of the Periphery, but it looks like it didn't produce needed results. This packages aren't got their own targets but added as libraries in FrameWorks, Libraries and Embedded Content in General properties of my main target. Is there any possibilities to add list of "interesting" local packages to Periphery scan properties?

**Comment by im-jersh** [comment] 2023-09-26 21:24
@ileitch would love to offer any help i can to move this forward! would you be able to point out the specific pbxproj configurations that you were hoping to see in my [example project](https://github.com/im-jersh/PeripheryLocalPackages)? with a little direction i could dig into this myself and see if i can work out this issue

**Comment by rogerluan** [comment] 2023-09-26 22:02
I'm also interested in this 👀 subscribing to this thread

**Comment by ileitch** [comment] 2023-09-27 10:13
@im-jersh Sorry, I missed your previous comment with the example project, thanks for providing this! The crux of the issue here is that in Xcode <= 14.3.1 local package are poorly represented in the pbxproj. Periphery's support is a hack that scans through `PBXFileReference` to find the paths to the local packages. Your example project does not contain these references.

It's simple enough to fix though. Using Xcode <= 14.3.1 (explained below), add the local packages on the `Package Dependencies` section of the project.

<img width="292" alt="Screenshot 2023-09-27 at 11 05 30" src="https://github.com/peripheryapp/periphery/assets/48235/1ae7b630-3cc4-49b1-8dd7-63232eb48c34">

After the adding the package, it may not show up in the package list (good job, Apple), but it will have modified the pbxproj with the `PBXFileReference`.

Now when you run `periphery scan --setup`, you'll see the local package targets:

<img width="591" alt="Screenshot 2023-09-27 at 11 09 35" src="https://github.com/peripheryapp/periphery/assets/48235/08c7a632-baf6-48dc-b061-53ddcd69f477">

In Xcode 15, Apple have improved the internal presentation of local packages, however [tuist/XcodeProj](https://github.com/tuist/XcodeProj) doesn't yet support parsing this new format, so for now you'll need to use 14.3 when adding local packages.

**Comment by im-jersh** [comment] 2023-10-03 03:33
that was it! appreciate the thoughtful response. could've sworn i had tested that configuration but i guess not 🤷. 

not surprised this is what was causing my issues in the actual workspace i'm attempting to analyze. that one has quite a few more local packages within it and i likely elected to forego adding that local package reference to the pbxproj since it's not necessary for compilation/linking.

and thank you for pointing out the lack of Xcode 15 support. i'm actually in the the tail end of validating local builds and updating our CI to Xcode 15 so this info will likely save me a few hours of headaches.

are there any documentation updates that i could offer to open in a PR to help anyone else with this workspace configuration and looking to integrate Periphery? maybe just in the README?

**Comment by im-jersh** [comment] 2023-10-03 03:58
looks like you also need to include the frameworks under the target's `Framework, Libraries, and Embedded Content` in order for Periphery to see them as build targets that can be analyzed

**Comment by im-jersh** [comment] 2023-10-03 04:04
i also just confirmed this worked for the actual workspace i want to analyze!!

**Comment by alinfarcas12** [comment] 2024-01-23 15:37
This still is an issue on XCode 15. The local package target is not visible to periphery even though the scheme is visible.
Tested on 2.18.0

**Closed** 2024-06-15 13:33 UTC
Labels: bug, question
